get all users
Slightly-Techie/crm-api pull request #41
Opened 2023-01-18 21:00 UTC by RansfordGenesis

2023-01-19 22:11 UTC, JerryAgbesi approved these changes

2023-01-23 22:24 UTC, blitzblade requested changes
Add tests for this

2023-02-08 21:48 UTC, blitzblade commented on test/test_admin.py
> +    res=client.post(
Why is the request a post request when the endpoint is a get endpoint?

2023-02-08 21:49 UTC, blitzblade commented on test/test_admin.py
> +    assert res.json()
Your test should check for an expected record you know is there.
You can create a user for instance, and then try fetching and asserting that the name of the first user item matches the one you created.

2023-02-23 21:40 UTC, blitzblade commented on test/test_users.py
> +    # uncertain if status_code will be included with the list of users
Did you run this test locally to see if there are any errors?

Looks like you're trying to fetch status code from a dictionary

2023-04-06 21:56 UTC, blitzblade approved these changes

2023-05-27 09:10 UTC, closed without merging